name: SCA
on:
 push:
   branches: [ master ]
 pull_request:
   branches: [ master ]

jobs:
 conviso-sast:
   runs-on: ubuntu-latest
   container:
     image: convisoappsec/flowcli
     env:
       FLOW_API_KEY:  ${{Ndec6g9VZ0pkbAn5gCgVt2t5BhUyYDtS8BDxUrDpV_Q}}
       FLOW_PROJECT_CODE: ${{00xFUoWOm9DtJBXg}}
   steps:
   - uses: actions/checkout@v2

   - name: Run SAST
     run: conviso sast run
