name: SAST
on:
 push:
   branches: [ main ]
 pull_request:
   branches: [ main ]

jobs:
 conviso-sast:
   runs-on: ubuntu-latest
   container:
     image: convisoappsec/flowcli
     env:
       FLOW_API_KEY:  "Njq4GaCN9ni-Id4l-XNPGF3y-x5-axd9USHX_q5FxyU"
       FLOW_PROJECT_CODE: "00xFUoWOm9DtJBXg"
   steps:
   - uses: actions/checkout@v2

   - name: Run SAST
     run: conviso sast run
